# Welcome to Jekyll!
#

# Site settings
title: ICT Architecture Branch
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown

sass:
  style: compressed

timezone: Australia/Sydney

# Build settings
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - package.json
  - CHANGELOG.md
  - README.md
  - LICENSE.md
  - assets/sass
  - vendor
  - Staticfile
  - .jekyll-cache
  - .git
  - .circleci

# Plugin settings
plugins:
   - jekyll-last-modified-at
   
algolia:
  application_id: "AAA"
  index_name: "BBB"
  search_only_api_key: "CCC"