apiVersion : apps/v1
kind: Deployment
metadata:
  name: archwebsite 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archwebsite
  template:
    metadata:
      labels:
        app: archwebsite 
    spec:
      containers:
        - name: archwebsite 
          image: archwebsiteacr.azurecr.io/archwebsite
          ports:
          - containerPort: 80