apiVersion : apps/v1
kind: Deployment
metadata:
  name: patternpilotimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patternpilotimage
  template:
    metadata:
      labels:
        app: patternpilotimage 
    spec:
      containers:
        - name: patternpilotimage 
          image: patternpilot.azurecr.io/patternpilotimage
          ports:
          - containerPort: 80