on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: patternpilot.azurecr.io
        username: ${{ secrets.acr_patternpilot_username }}
        password: ${{ secrets.acr_patternpilot_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t patternpilot.azurecr.io/patternpocaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push patternpilot.azurecr.io/patternpocaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_patternpocaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep patternpilotnamespace | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace patternpilotnamespace`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: patternpilotnamespace
        container-registry-url: patternpilot.azurecr.io
        container-registry-username: ${{ secrets.acr_patternpilot_username }}
        container-registry-password: ${{ secrets.acr_patternpilot_password }}
        secret-name: patternpocakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: patternpilotnamespace
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          patternpilot.azurecr.io/patternpocaks:${{ github.sha }}
        imagepullsecrets: |
          patternpocakdockerauth
